name: DRZ Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # NAYA FIX: Agar keystore nahi hai, toh automatic generate kar lo
    - name: Generate Debug Keystore
      run: |
        if [ -f "debug.keystore.base64" ]; then
          base64 -d debug.keystore.base64 > debug.keystore
        else
          echo "Generating default debug keystore to bypass error..."
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        fi

    - name: Setup Gradle Cache
      uses: gradle/actions/setup-gradle@v3

    - name: Generate Gradle Wrapper
      run: gradle wrapper

    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew

    - name: Build Debug APK with Gradle
      run: ./gradlew assembleDebug

    - name: Upload DRZ Build APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DRZ-Build-APK
        path: "**/build/outputs/apk/debug/*.apk"
        retention-days: 7
